### ISSUE TITLE
slow performance

### ISSUE THREAD

**Issue by andkom** [SolarRepublic/wasm-secp256k1#5]
```
tiny-secp256k1 1.458 s
@bitauth/libauth 0.511 s
@solar-republic/wasm-secp256k1 1.228 s
```

bench code:

```javascript
import * as ecc from 'tiny-secp256k1';
import {instantiateSecp256k1} from '@bitauth/libauth';
import {initWasmSecp256k1} from '@solar-republic/wasm-secp256k1'

async function main() {
  const ecc2 = await instantiateSecp256k1();
  const ecc3 = await initWasmSecp256k1();

  const iter = 10000;
  const pk = new Uint8Array(Buffer.from('0000000000000000000000000000000000000000000000000000000000000001', 'hex'));

  let start = Date.now();

  for (let i = 0; i < iter; i++) {
    ecc.pointFromScalar(pk);
  }

  console.log('tiny-secp256k1', (Date.now() - start) / 1000, 's');

  start = Date.now();

  for (let i = 0; i < iter; i++) {
    ecc2.derivePublicKeyCompressed(pk);
  }

  console.log('@bitauth/libauth', (Date.now() - start) / 1000, 's');

  start = Date.now();

  for (let i = 0; i < iter; i++) {
    ecc3.sk_to_pk(pk);
  }

  console.log('@solar-republic/wasm-secp256k1', (Date.now() - start) / 1000, 's');
}

main();
```

**Comment by blake-regalia** [comment]
Thanks for opening an issue! Very interesting to compare performance of these libs.

I'd be willing to bet the reason that `@bitauth/libauth` (which this repo originally forked long ago) is getting faster performance is due to the fact that they are not [randomizing the context](https://github.com/SolarRepublic/wasm-secp256k1/blob/main/src/api/secp256k1.ts#L183-L194) for each operation on the secret key, however we are. This is recommended by the libsecp256k1 authors in order to provide better protection against side-channel attacks on the CPU. Considering this is an important security feature, I'd say it is not something we're interested in removing for the sake of performance.
